# Generated by Django 4.2.3 on 2026-01-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_text_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='course',
            new_name='question',
        ),
    ]
